/* automatically generated by rust-bindgen 0.56.0 */

pub const MonoTokenType_MONO_TOKEN_MODULE: MonoTokenType = 0;
pub const MonoTokenType_MONO_TOKEN_TYPE_REF: MonoTokenType = 16777216;
pub const MonoTokenType_MONO_TOKEN_TYPE_DEF: MonoTokenType = 33554432;
pub const MonoTokenType_MONO_TOKEN_FIELD_DEF: MonoTokenType = 67108864;
pub const MonoTokenType_MONO_TOKEN_METHOD_DEF: MonoTokenType = 100663296;
pub const MonoTokenType_MONO_TOKEN_PARAM_DEF: MonoTokenType = 134217728;
pub const MonoTokenType_MONO_TOKEN_INTERFACE_IMPL: MonoTokenType = 150994944;
pub const MonoTokenType_MONO_TOKEN_MEMBER_REF: MonoTokenType = 167772160;
pub const MonoTokenType_MONO_TOKEN_CUSTOM_ATTRIBUTE: MonoTokenType = 201326592;
pub const MonoTokenType_MONO_TOKEN_PERMISSION: MonoTokenType = 234881024;
pub const MonoTokenType_MONO_TOKEN_SIGNATURE: MonoTokenType = 285212672;
pub const MonoTokenType_MONO_TOKEN_EVENT: MonoTokenType = 335544320;
pub const MonoTokenType_MONO_TOKEN_PROPERTY: MonoTokenType = 385875968;
pub const MonoTokenType_MONO_TOKEN_MODULE_REF: MonoTokenType = 436207616;
pub const MonoTokenType_MONO_TOKEN_TYPE_SPEC: MonoTokenType = 452984832;
pub const MonoTokenType_MONO_TOKEN_ASSEMBLY: MonoTokenType = 536870912;
pub const MonoTokenType_MONO_TOKEN_ASSEMBLY_REF: MonoTokenType = 587202560;
pub const MonoTokenType_MONO_TOKEN_FILE: MonoTokenType = 637534208;
pub const MonoTokenType_MONO_TOKEN_EXPORTED_TYPE: MonoTokenType = 654311424;
pub const MonoTokenType_MONO_TOKEN_MANIFEST_RESOURCE: MonoTokenType = 671088640;
pub const MonoTokenType_MONO_TOKEN_GENERIC_PARAM: MonoTokenType = 704643072;
pub const MonoTokenType_MONO_TOKEN_METHOD_SPEC: MonoTokenType = 721420288;
pub const MonoTokenType_MONO_TOKEN_STRING: MonoTokenType = 1879048192;
pub const MonoTokenType_MONO_TOKEN_NAME: MonoTokenType = 1895825408;
pub const MonoTokenType_MONO_TOKEN_BASE_TYPE: MonoTokenType = 1912602624;
pub type MonoTokenType = ::std::os::raw::c_int;
